/**
 * @posteragent/agent-trend-finder — types
 *
 * Provider-agnostic. Depends on TrendSource (fetches recent videos in a
 * niche), TranscriptSource (optional, pulls captions for hook mining),
 * and an LLMClient for brief generation.
 *
 * Pipeline:
 *   niche[]
 *     → fetchTrending (per-niche fan-out, parallel)
 *     → extractPatterns (title patterns + thumbnail features + velocity)
 *     → clusterTopics  (LLM-light: keyword + cosine-style overlap)
 *     → findGaps       (topics with weak existing coverage)
 *     → genBriefs      (LLM produces ContentBrief per gap)
 *     → TrendReport
 *
 * The handler then turns each ContentBrief into a queued 'write' task
 * for the Content/Writer agent.
 */

// ─── Inputs ───────────────────────────────────────────────────────────

export interface Video {
  id: string
  url: string
  title: string
  description: string
  channelId?: string
  channelTitle?: string
  publishedAt?: string
  /** Engagement signals. */
  views?: number
  likes?: number
  comments?: number
  /** Length in seconds, if known. */
  durationSec?: number
  thumbnailUrl?: string
  /** Niche tag this video was fetched under. */
  niche: string
}

export interface TrendSource {
  readonly name: string
  /** Fetches recent / trending videos for a given niche. */
  fetchTrending(input: {
    niche: string
    /** ISO; default ~ 7 days ago. */
    publishedAfter?: string
    maxResults?: number
    /** ISO 3166-1 alpha-2 region for trends. Default 'US'. */
    region?: string
    signal?: AbortSignal
  }): Promise<Video[]>
}

export interface TranscriptSource {
  readonly name: string
  /** Returns plaintext transcript (best-effort). Falls back to empty string. */
  fetchTranscript(input: {
    videoId: string
    signal?: AbortSignal
  }): Promise<string>
}

// ─── LLM ──────────────────────────────────────────────────────────────

export interface LLMMessage {
  role: 'system' | 'user' | 'assistant'
  content: string
}

export interface LLMClient {
  readonly name: string
  complete(input: {
    messages: LLMMessage[]
    model?: string
    maxTokens?: number
    temperature?: number
    signal?: AbortSignal
  }): Promise<{
    text: string
    model: string
    usage: { inputTokens: number; outputTokens: number }
  }>
}

// ─── Extracted patterns ──────────────────────────────────────────────

export interface TitlePattern {
  /** A normalised template: "How to X in Y" / "I tried X for Y days" / "X vs Y". */
  template: string
  /** Number of videos in the input that matched the template. */
  count: number
  /** Median views across matched videos. */
  medianViews: number
  examples: Array<{ id: string; title: string; views?: number }>
}

export interface HookStyle {
  /**
   * Hook style detected from the first ~10 seconds of transcripts or
   * from title intro words: "question", "cold-open-claim", "story",
   * "stat-shock", "list-tease", "controversy".
   */
  kind: string
  count: number
  examples: Array<{ id: string; title: string; firstLine?: string }>
}

export interface ThumbnailPattern {
  /** A heuristic descriptor: "face-zoom", "text-overlay-bold", "split-comparison", "object-isolate". */
  kind: string
  count: number
  examples: Array<{ id: string; thumbnailUrl?: string }>
}

export interface VelocityMetric {
  videoId: string
  /** Views per hour since publish. */
  viewsPerHour: number
  /** Engagement ratio: (likes + comments) / views. */
  engagementRate: number
}

// ─── Clusters + Gaps ─────────────────────────────────────────────────

export interface TopicCluster {
  id: string
  niche: string
  /** A short human label produced by the LLM (or keyword-derived). */
  label: string
  videoIds: string[]
  /** Approximate aggregate views across cluster. */
  totalViews: number
  /** Median views across cluster — proxy for topic strength. */
  medianViews: number
}

export interface ContentGap {
  niche: string
  /** Why this is a gap: "few results", "low-quality coverage", "outdated", "no English coverage". */
  reason: string
  /** A short topic label the brief should be written about. */
  topic: string
  /** Cluster id this gap was derived from, if any. */
  clusterId?: string
  /** Estimated demand on a 0..100 scale — derived from velocity + comments. */
  demandScore: number
  /** Estimated competition on a 0..100 scale — lower = easier. */
  competitionScore: number
}

// ─── Brief ───────────────────────────────────────────────────────────

export interface ContentBrief {
  niche: string
  topic: string
  /** Working title, generated by the LLM. */
  workingTitle: string
  /** Hook the writer should open with. */
  hook: string
  /** Bullet outline. */
  outline: string[]
  /** Format hint: 'video' | 'short' | 'blog' | 'thread'. */
  format: 'video' | 'short' | 'blog' | 'thread'
  /** Approximate length target. */
  targetLengthMin?: number
  targetLengthSec?: number
  /** Why this brief beats existing coverage. */
  differentiator: string
  /** Source video ids the brief is responding to. */
  inspiredBy: string[]
}

// ─── Report ──────────────────────────────────────────────────────────

export interface TrendReport {
  niches: string[]
  videos: Video[]
  titlePatterns: TitlePattern[]
  hooks: HookStyle[]
  thumbnails: ThumbnailPattern[]
  velocity: VelocityMetric[]
  clusters: TopicCluster[]
  gaps: ContentGap[]
  briefs: ContentBrief[]
  timings: {
    fetchMs: number
    extractMs: number
    clusterMs: number
    gapMs: number
    briefMs: number
    totalMs: number
  }
  usage: {
    clusterInputTokens: number
    clusterOutputTokens: number
    briefInputTokens: number
    briefOutputTokens: number
  }
}

// ─── Pipeline config ─────────────────────────────────────────────────

export interface TrendConfig {
  /** Window in hours to look back when fetching trending. Default 168 (7d). */
  windowHours: number
  /** Max videos per niche. Default 50. */
  videosPerNiche: number
  /** Region for trends (alpha-2). Default 'US'. */
  region: string
  /** Topic clusters max per niche. Default 8. */
  maxClustersPerNiche: number
  /** Max briefs to generate per report. Default 5. */
  maxBriefs: number
  /** When set, only generate briefs for gaps with demandScore ≥ this. Default 50. */
  minDemandScore: number
  /** When set, only generate briefs for gaps with competitionScore ≤ this. Default 70. */
  maxCompetitionScore: number
  /** Per-stage timeouts in ms. */
  fetchTimeoutMs: number
  clusterTimeoutMs: number
  briefTimeoutMs: number
  /** Optional model overrides. */
  clusterModel?: string
  briefModel?: string
}

export const DEFAULT_CONFIG: TrendConfig = {
  windowHours: 168,
  videosPerNiche: 50,
  region: 'US',
  maxClustersPerNiche: 8,
  maxBriefs: 5,
  minDemandScore: 50,
  maxCompetitionScore: 70,
  fetchTimeoutMs: 30_000,
  clusterTimeoutMs: 45_000,
  briefTimeoutMs: 60_000,
}
