/**
 * Stage 2 — scaffold the file tree for the chosen template.
 *
 * Each template returns a list of `ScaffoldedFile`. Files flagged
 * `needsCodegen: true` are placeholders the codegen pass will rewrite
 * with LLM output. Everything else is final.
 */

import type { AppSpec, ScaffoldedApp, ScaffoldedFile } from '../types.js'

function commonRoot(spec: AppSpec): ScaffoldedFile[] {
  const featureList = spec.features.length
    ? spec.features.map((f) => `- ${f}`).join('\n')
    : '_none_'
  return [
    {
      path: 'README.md',
      content: `# ${spec.name}\n\n${spec.pitch}\n\n## Features\n\n${featureList}\n\n_Generated by @posteragent/agent-app-builder._\n`,
    },
    {
      path: '.gitignore',
      content: ['node_modules', 'dist', '.next', '.env*', ''].join('\n'),
    },
  ]
}

function nextAppFiles(spec: AppSpec): ScaffoldedFile[] {
  const pages = spec.pages.map((p) => ({
    path: `app${p.path === '/' ? '' : p.path}/page.tsx`,
    content: `// PURPOSE: ${p.purpose}\nexport default function Page() {\n  return <main className="p-8">/* PLACEHOLDER */</main>\n}\n`,
    needsCodegen: true,
  }))
  return [
    ...commonRoot(spec),
    {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: spec.name,
          private: true,
          scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
          dependencies: { next: '^14', react: '^18', 'react-dom': '^18' },
        },
        null,
        2,
      ) + '\n',
    },
    {
      path: 'app/layout.tsx',
      content: `export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return <html><body>{children}</body></html>\n}\n`,
    },
    ...pages,
  ]
}

function honoApiFiles(spec: AppSpec): ScaffoldedFile[] {
  const routes = spec.pages
    .map(
      (p) =>
        `// PURPOSE: ${p.purpose}\napp.all('${p.path}', (c) => c.json({ ok: true, path: '${p.path}' }))`,
    )
    .join('\n')
  return [
    ...commonRoot(spec),
    {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: spec.name,
          private: true,
          scripts: {
            dev: 'wrangler dev',
            deploy: 'wrangler deploy',
          },
          dependencies: { hono: '^4' },
          devDependencies: { wrangler: '^3', typescript: '^5' },
        },
        null,
        2,
      ) + '\n',
    },
    {
      path: 'wrangler.toml',
      content: `name = "${spec.name}"\nmain = "src/index.ts"\ncompatibility_date = "2025-01-01"\n`,
    },
    {
      path: 'src/index.ts',
      content: `import { Hono } from 'hono'\n\nconst app = new Hono()\n\n${routes}\n\nexport default app\n`,
      needsCodegen: true,
    },
  ]
}

function staticSiteFiles(spec: AppSpec): ScaffoldedFile[] {
  const sections = spec.pages
    .map((p) => `    <section id="${p.path.replace(/\W+/g, '') || 'home'}"><h2>${p.purpose}</h2><!-- PLACEHOLDER --></section>`)
    .join('\n')
  return [
    ...commonRoot(spec),
    {
      path: 'index.html',
      content: `<!doctype html>\n<html><head><meta charset="utf-8"><title>${spec.name}</title></head>\n<body>\n  <h1>${spec.name}</h1>\n  <p>${spec.pitch}</p>\n${sections}\n</body></html>\n`,
      needsCodegen: true,
    },
  ]
}

function reactSpaFiles(spec: AppSpec): ScaffoldedFile[] {
  return [
    ...commonRoot(spec),
    {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: spec.name,
          private: true,
          scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
          dependencies: { react: '^18', 'react-dom': '^18' },
          devDependencies: { vite: '^5', '@vitejs/plugin-react': '^4' },
        },
        null,
        2,
      ) + '\n',
    },
    {
      path: 'index.html',
      content: `<!doctype html><html><head><title>${spec.name}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n`,
    },
    {
      path: 'src/main.tsx',
      content: `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport App from './App'\ncreateRoot(document.getElementById('root')!).render(<App />)\n`,
    },
    {
      path: 'src/App.tsx',
      content: `// PURPOSE: ${spec.pitch}\nexport default function App() {\n  return <main className="p-8"><h1>${spec.name}</h1></main>\n}\n`,
      needsCodegen: true,
    },
  ]
}

export function scaffold(spec: AppSpec): ScaffoldedApp {
  switch (spec.template) {
    case 'next-app':
      return { spec, files: nextAppFiles(spec) }
    case 'hono-api':
      return { spec, files: honoApiFiles(spec) }
    case 'static-site':
      return { spec, files: staticSiteFiles(spec) }
    case 'react-spa':
      return { spec, files: reactSpaFiles(spec) }
  }
}
